services:
  # Web service for the full stack application
  - type: web
    name: conferencehub-app
    runtime: node
    buildCommand: |
      echo "Starting build process..."
      npm install
      echo "Root dependencies installed"
      cd client
      npm install
      echo "Client dependencies installed"
      npm run build
      echo "Client build completed"
      cd ..
      echo "Build directory contents:"
      ls -la client/dist || echo "Dist directory not found"
      echo "Assets directory contents:"
      ls -la client/dist/assets || echo "Assets directory not found"
      echo "Checking for critical files:"
      find client/dist -name "*.js" -o -name "*.css" | head -10
    startCommand: NODE_ENV=production node start.js
    plan: free
    region: singapore
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DB_URL
        fromDatabase:
          name: conferencehub-db
          property: connectionString
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
      - key: TELEGRAM_GATEWAY_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VITE_TELEGRAM_BOT_USERNAME
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: APP_URL
        sync: false
      - key: VITE_YANDEX_GEOCODER_API_KEY
        sync: false
      - key: VITE_PROTECTION_PLAN_PERCENTAGE
        sync: false
      - key: PROTECTION_PLAN_PERCENTAGE
        sync: false
      - key: ESKIZ_EMAIL
        sync: false
      - key: ESKIZ_SECRET_CODE
        sync: false
      - key: ESKIZ_BASE_URL
        sync: false
      - key: ESKIZ_FROM
        sync: false
      
databases:
  - name: conferencehub-db
    plan: free
    region: singapore
    databaseName: conferencehub