services:
  # Web service for the full stack application
  - type: web
    name: airbnb-clone-app
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && node ./node_modules/.bin/vite build && cd ..
    startCommand: cd api && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: airbnb-clone-db
          property: connectionString

databases:
  - name: airbnb-clone-db
    plan: free
    databaseName: airbnb_clone